### PR TITLE
Osx arm

### PR DESCRIPTION
**Pull request by JohanMabille**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marimeireles** [comment]
Oh... I'm trying to do the same thing I guess, Johan.
Any ideas on what's up? Cheers.

**Comment by JohanMabille** [comment]
cpp-tabulate 1.4 is missing for osx-arm64, I built cpp-tabulate 1.5 but this one is backward incompatible. The issue regarding xeus-zmq is weird, it should use 1.0.2 not 1.0.1.

**Comment by JohanMabille** [comment]
here we go: https://github.com/conda-forge/cpp-tabulate-feedstock/pull/9

**Comment by JohanMabille** [comment]
@marimeireles another issue is that we have a max pin x.x of nlohmann_json in the feedstock of the xeus packages, and an upper bound set to 3.10 in xeus and xeus-zmq :s

**Comment by marimeireles** [comment]
@JohanMabille but that shouldn't be an impediment, right?
Because the other xeus kernel don't need a higher version...
I've tried to build your branch locally in my machine and getting the same libcxx error.
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-arm64: {"libcxx[version='>=12.0.0']", "libcxx[version='>=11.0.1|>=11.1.0|>=12.0.0']", "xtl[version='>=0.7.0,<0.8']", "libcxx[version='>=11.0.0|>=11.0.1|>=11.1.0|>=14.0.6']", "libcxx[version='>=11.0.0|>=11.0.1|>=11.1.0']", "libsodium[version='>=1.0.18,<1.0.19.0a0']", "libcxx[version='>=14.0.6']"}
```
And I don't get it even when I lock it to 11.1.0 it fails the same way 😔

**Comment by JohanMabille** [comment]
> but that shouldn't be an impediment, right?

As long as you don't have another dependencies that itself depends on nlohmann_json without the same upper bound, it's fine. Unfortunately, xvega is build with nlohmann_json 3.11, thus the conflict we see in this PR.

Regarding the libcxx issue, I haven't encountered it yet on this PR. Something that could help is to make an environment file with the same dependencies and constraints as in this feedstock, and try to create an environment from it with a recent version of mamba and the error messages activated (you need to add `experimental_sat_error_message: true` to your condarc file). This will give you a more precise error message.

**Comment by JohanMabille** [comment]
~~DO NOT MERGE YET!~~

~~For an unknown reason, the build does not use the last build of xeus-zmq on linux.~~

**Comment by marimeireles** [comment]
Wooot 🎉
Awesome!

**Pull request merged**
